secrets:
  - kmsKeyName: projects/voices-to-emotions/locations/global/keyRings/MONGODB_CONN_STRING/cryptoKeys/MONGODB_CONN_STRING
    secretEnv:
      MONGODB_CONN_STRING: <base64-encoded encrypted secret>

steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "functions",
        "deploy",
        "mfcc",
        "--trigger-http",
        "--runtime",
        "python37",
        "--memory",
        "2048MB",
        "--region",
        "europe-west1"
      ]
    dir: "functions/mfcc"
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      "functions",
      "deploy",
      "storage_trigger",
      "--trigger-resource",
      "voices-to-emotions-call-data",
      "--trigger-event",
      "google.storage.object.finalize",
      "--runtime",
      "nodejs8",
      "--memory",
      "1024MB",
      "--region",
      "europe-west1"
    ]
    secretEnv: ['MONGODB_CONN_STRING']
    dir: "functions/storage_trigger"