steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "functions",
        "deploy",
        "mfcc_post",
        "--trigger-http",
        "--runtime",
        "python37",
        "--memory",
        "2048MB",
        "--region",
        "europe-west1"
      ]
    dir: "functions/mfcc"
