steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      [
        "kms",
        "decrypt",
        "--ciphertext-file=.env.enc"
        "--plaintext-file=.env"
        "--location=global"
        "--keyring=MONGODB_CONN_STRING"
        "--key=MONGODB_CONN_STRING"
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "functions",
        "deploy",
        "mfcc",
        "--trigger-http",
        "--runtime",
        "python37",
        "--memory",
        "2048MB",
        "--region",
        "europe-west1"
      ]
    dir: "functions/mfcc"
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      "functions",
      "deploy",
      "storage_trigger",
      "--trigger-resource",
      "voices-to-emotions-call-data",
      "--trigger-event",
      "google.storage.object.finalize",
      "--runtime",
      "nodejs8",
      "--memory",
      "1024MB",
      "--region",
      "europe-west1",
      "--env-vars-file",
      ".env"
    ]
    dir: "functions/storage_trigger"
