steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "functions",
        "deploy",
        "mfcc",
        "--trigger-http",
        "--runtime",
        "python37",
        "--memory",
        "2048MB",
        "--region",
        "europe-west1"
      ]
    dir: "functions/mfcc"
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      "functions",
      "deploy",
      "storage_trigger",
      "--trigger-resource",
      "voices-to-emotions-call-data",
      "--trigger-event",
      "google.storage.object.finalize",
      "--runtime",
      "nodejs8",
      "--memory",
      "1024MB",
      "--region",
      "europe-west1",
      "--set-env-vars",
      "MONGODB_CONN_STRING=$_MONGODB_CONN_STRING_"
    ]
    secretEnv: ["_MONGODB_CONN_STRING_"]
    dir: "functions/storage_trigger"

secrets:
  - kmsKeyName: projects/voices-to-emotions/locations/global/keyRings/MONGODB_CONN_STRING/cryptoKeys/MONGODB_CONN_STRING
    secretEnv:
      _MONGODB_CONN_STRING_: CiQATqeISdkPbb50KHkCx4W0ZUrsk/UYJ5xQR1TI5LecR2lVHnsSIQAz3GQ0NZUK1AN858TZ7w4GEMCaB38k6eCS5siSxidVkQ==
